server:
  port: 8091
spring:
  application:
    name: paymentapp

  datasource:
    url: jdbc:mysql://localhost:3306/paymentapp?createDatabaseIfNotExist=true
    username: root
    password: educacaovirtual2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
